### ISSUE TITLE
i3-volume causes an error in notify-send.py

### ISSUE THREAD

**Issue by rjekker** [hastinbe/i3-volume#30] opened 2021-04-26 22:08 UTC
See https://github.com/phuhl/notify-send.py/issues/19. When I run your script like this:

```
USE_NOTIFY_SEND_PY=true ./volume -n -t i3status -u SIGUSR1 up 5
```

This causes the following error:

```
  File "/home/reindert/.local/lib/python3.7/site-packages/notify_send_py/notify_send_py.py", line 126, in notify
    conn = Client(pidf.read())
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 487, in Client
    family = family or address_type(address)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 108, in address_type
    raise ValueError('address type of %r unrecognized' % address)
ValueError: address type of b'' unrecognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/reindert/.local/bin/notify-send.py", line 8, in <module>
    sys.exit(main())
  File "/home/reindert/.local/lib/python3.7/site-packages/notify_send_py/notify_send_py.py", line 218, in main
    NotifySendPyCLI()
  File "/home/reindert/.local/lib/python3.7/site-packages/notify_send_py/notify_send_py.py", line 211, in __init__
    dontQuitOnAction=args.dontQuitOnAction
  File "/home/reindert/.local/lib/python3.7/site-packages/notify_send_py/notify_send_py.py", line 132, in notify
    pidf.write(listener.address)
TypeError: a bytes-like object is required, not 'str'
```

Using python 3.7.3 on Debian buster.

**Comment by hastinbe** [comment] 2021-04-26 23:45
I was able to reproduce the issue on my version of notify-send.py, but pulling in the latest from their repo the problem was fixed in commit https://github.com/phuhl/notify-send.py/commit/99415b4ea64cd201bcb2e93b28459b2dac2c5ab8

```
git clone https://github.com/phuhl/notify-send.py && cd notify-send.py && python3 -m pip install .
```

**Closed** 2021-04-29 08:24 UTC

**Comment by phuhl** [comment] 2021-05-04 14:48
Thanks for helping out @hastinbe , great it got resolved.
